services:
  app:
    build: .
    container_name: neptune
    restart: no
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - neptune_network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
  
  db:
    image: mysql:8.0
    container_name: neptune_db
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neptune
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - neptune_network
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: neptune_nginx
    restart: no
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - neptune_network

  composer:
    image: composer:2.7
    container_name: laravel_composer
    working_dir: /var/www
    volumes:
      - .:/var/www

networks:
  neptune_network:

volumes:
  dbdata:
